version: '3'

tasks:
  generate:
    desc: "generate grpc contracts"
    cmds:
    - protoc -I proto proto/auth.proto --go_out=./generate --go_opt=paths=source_relative --go-grpc_out=./generate --go-grpc_opt=paths=source_relative proto/auth.proto
    #  - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/auth.proto